version: '2'
services:

  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    links:
      - mysql
      - composer
    ports:
      - "8000:8000"
      - "4443:443"
    volumes:
      - ../:/app/
      - ./:/docker/
    volumes_from:
      - storage
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - etc/environment.yml
    environment:
      - VIRTUAL_HOST=.app.boilerplate.docker
      - VIRTUAL_PORT=80
      - POSTFIX_RELAYHOST=[mail]:1025
  #######################################
  # Composer Docker container
  #######################################
  composer:
    build:
      context: docker/composer/
    volumes_from:
      - storage

  #######################################
  # MySQL server
  #######################################
  mysql:
    build:
      context: docker/mysql/
      dockerfile: MySQL-5.6.Dockerfile
    ports:
      - 23306:3306
    volumes_from:
      - storage
    env_file:
      - etc/environment.yml

  #######################################
  # Storage
  #######################################
  storage:
    build:
      context: docker/storage/
    volumes:
      - /storage
