<?php

/**
 * @file
 * Defines the theme for the calendar block.
 */
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function wiki_theme($existing, $type, $theme, $path) {
  return [
    'wiki_page' => [
      'variables' => [
        'parameters' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter() for the search_block_form form.
 *
 * @see \Drupal\wiki\Form\WikiBlockForm
 */
function wiki_form_wiki_block_form_alter(&$form, FormStateInterface $form_state) {
  $form['form_build_id']['#access'] = FALSE;
  $form['form_token']['#access'] = FALSE;
  $form['form_id']['#access'] = FALSE;
}
